### ISSUE TITLE
ODHv2 not installing TrustyAI CRDs when used in `devFlags` mode

### ISSUE THREAD

**Issue by ruivieira** [trustyai-explainability/trustyai-service-operator#141]
When deploying using a DSC with

```
 trustyai:
      devFlags:
        manifests:
          - contextDir: config
            uri: >-
              https://github.com/trustyai-explainability/trustyai-service-operator/tarball/mybranch
      managementState: Managed
```
The following error occurs:

```
error: resource mapping not found for name: “trustyai-service” namespace: “” from “tests/resources/trustyai/trustyai_crd.yaml”: no matches for kind “TrustyAIService” in version “[trustyai.opendatahub.io.trustyai.opendatahub.io/v1alpha1](http://trustyai.opendatahub.io.trustyai.opendatahub.io/v1alpha1)”
ensure CRDs are installed first
```

ODH operator logs:

```
W1107 11:15:03.267949 1 reflector.go:424] go/pkg/mod/k8s.io/client-go@v0.26.4/tools/cache/reflector.go:169: failed to list *v1alpha1.TrustyAIService: the server could not find the requested resource (get trustyaiservices.trustyai.opendatahub.io.trustyai.opendatahub.io)
E1107 11:15:03.267976 1 reflector.go:140] go/pkg/mod/k8s.io/client-go@v0.26.4/tools/cache/reflector.go:169: Failed to watch *v1alpha1.TrustyAIService: failed to list *v1alpha1.TrustyAIService: the server could not find the requested resource (get trustyaiservices.trustyai.opendatahub.io.trustyai.opendatahub.io)
```
