### ISSUE TITLE
Correct labels in TrustyAI OAuth Service

### ISSUE THREAD

**Issue by ruivieira** [trustyai-explainability/trustyai-service-operator#154]
The non-authenticated service (`trustyai-service`) has labels

```
 labels:
    app: trustyai-service
    app.kubernetes.io/instance: trustyai-service
    app.kubernetes.io/name: trustyai-service
    app.kubernetes.io/part-of: trustyai
    app.kubernetes.io/version: 0.1.0
```

But the authenticated one (`trustyai-service-tls`) has not.

```
 labels:
    trustyai-service-name: trustyai-service
```

Also the authenticated service name should be corrected.
