### ISSUE TITLE
Creating multiple `TrustyAIServices` prevents endpoint authentication

### ISSUE THREAD

**Issue by ruivieira** [trustyai-explainability/trustyai-service-operator#184]
### Problem

When creating multiple `TrustyAIServices`, endpoint authentication will fail.

### Steps to reproduce

Steps to reproduce using the CLI:

Assuming:
- A TrustyAI operator already deployed
- `$CLUSTER` is your cluster address.
- A `$TOKEN` as `export TOKEN=$(oc whoami -t)`
- No models are required to reproduce this

Create a namespace `test`. 
Add a first `TrustyAIService` in this namespace , using, for instance (`trustyai-test.yaml`)

```
apiVersion: trustyai.opendatahub.io/v1alpha1
kind: TrustyAIService
metadata:
  name: trustyai-service
spec:
  storage:
    format: "PVC"
    folder: "/inputs"
    size: "1Gi"
  data:
    filename: "data.csv"
    format: "CSV"
  metrics:
    schedule: "5s"
```
 and

```
oc apply -f trustyai-test.yaml -n test
```

Try the external endpoint:

```
curl -sk -H "Authorization: Bearer ${TOKEN}" https://trustyai-service-test.${CLUSTER}/info
```

This should provide a successful response (in terms of authentication, actual response might be `[]`).

Create a namespace `test2`. 
Add a `TrustyAIService` in this namespace , using, for instance the `trustyai-test.yaml` as before:

```
oc apply -f trustyai-test.yaml -n test2
```

Try the external endpoint:

```
curl -sk -H "Authorization: Bearer ${TOKEN}" https://trustyai-service-test2.${CLUSTER}/info
```

The request will now be unsuccessful in terms of authentication.
