### ISSUE TITLE
[Bug] Empty nodeSelectorTerm in Pod

### ISSUE THREAD

**Issue by tedhtchang** [trustyai-explainability/trustyai-service-operator#368]
Empty nodeLables in ResourceFlavor causes empty nodeSelectorTerms in the Pod created by the lmevaljob

Observed empty nodeSelectorTerms created by an lmevaljob
```
apiVersion: v1
kind: Pod
metadata:
  name: evaljob-sample-cf7rp
...
spec:
# This obj should not exist when nodeLabels is not provided
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - {} 
  containers:
...
```

Reproduce:
Makd sure:
1.  `- "trustyai.opendatahub.io/lmevaljob"`  in externalFramework in the kueue-manager-config; restart the keueu deployment.
2. Enable the `JOB_MGR` in the trustai deploy
3. Create cq, rf, lq
```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: "lm-eval-test"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cluster-queue"
spec:
  namespaceSelector: {} # match all.
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 4
      - name: "memory"
        nominalQuota: 40Gi
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "default-flavor"
# spec:
#  nodeLabels:
#    kubernetes.io/hostname: kueue-worker
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "lm-eval-test"
  name: "user-queue"
spec:
  clusterQueue: "cluster-queue"
EOF
```

4. Assign an lmevaljob to user-queue
```
cat <<EOF | kubectl create -f -
apiVersion: trustyai.opendatahub.io/v1alpha1
kind: LMEvalJob
metadata:
  labels:
    kueue.x-k8s.io/queue-name: user-queue
  generateName: evaljob-sample-
  namespace: "lm-eval-test"
spec:
  pod:
    container:
      resources:
        requests:
          cpu: 2
  suspend: true
  model: hf
  modelArgs:
  - name: pretrained
    value: EleutherAI/pythia-70m
  taskList:
    taskNames:
    - unfair_tos
  logSamples: true
  limit: "5"
EOF
```
